export const commandMap = [
  "Drill Up",
  "Drill Hold",
  "Drill Down",
  "Motor Forward",
  "Motor Stop",
  "Motor Back",
  "Rest chamber",
  "Water chamber",
  "Test chamber",
  "FPV ON",
  "FPV OFF",
  "Landing Legs",
  "Begin Auto Sequence",
];
